version: '3.8'

services:
  web:
    build: .
    volumes:
      - /opt/eden:/app 
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 Eden.wsgi:application"
