version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /opt/eden:/app
      - /opt/eden/db.sqlite3:/app/db.sqlite3
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    restart: always