# Generated by Django 5.0.7 on 2024-11-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='soil_moisture',
        ),
        migrations.AddField(
            model_name='group',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raspberry',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='Current soil moisture level', null=True),
        ),
        migrations.AlterField(
            model_name='raspberry',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raspberries', to='Website.group'),
        ),
        migrations.AlterField(
            model_name='raspberry',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Non Assigné'), ('assigned', 'Assigné'), ('offline', 'Hors Ligne')], default='unassigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='air_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sensorlocation',
            unique_together={('raspberry', 'location_name')},
        ),
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
