# Generated by Django 5.0.7 on 2024-12-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_sensordata_soil_moisture_group_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlocation',
            name='x_position',
            field=models.FloatField(blank=True, help_text='Position X dans la serre', null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='y_position',
            field=models.FloatField(blank=True, help_text='Position Y dans la serre', null=True),
        ),
        migrations.AlterField(
            model_name='sensorlocation',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='é2Current soil moisture level', null=True),
        ),
    ]
