# Generated by Django 5.0.7 on 2024-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_sensorlocation_x_position_sensorlocation_y_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity_max',
            field=models.FloatField(default=80.0, help_text='Maximum air humidity threshold'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity_min',
            field=models.FloatField(default=30.0, help_text='Minimum air humidity threshold'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_moisture_max',
            field=models.FloatField(default=70.0, help_text='Maximum soil moisture threshold'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_moisture_min',
            field=models.FloatField(default=20.0, help_text='Minimum soil moisture threshold'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_max',
            field=models.FloatField(default=35.0, help_text='Maximum temperature threshold'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_min',
            field=models.FloatField(default=10.0, help_text='Minimum temperature threshold'),
        ),
        migrations.AlterField(
            model_name='sensorlocation',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='Current soil moisture level', null=True),
        ),
    ]
