# Generated by Django 5.0.7 on 2025-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_sensordata_soil_moisture_alter_plant_humidity_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='water_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
