# Generated by Django 4.2.18 on 2025-02-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0005_sensordata_water_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
