# Generated by Django 4.2.18 on 2025-03-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='fan_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raspberry',
            name='pump_state',
            field=models.BooleanField(default=False),
        ),
    ]
