# Generated by Django 4.2.18 on 2025-04-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_raspberry_fan_state_raspberry_pump_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapayload',
            name='raspberry',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='DataPayload',
        ),
    ]
