# Generated by Django 4.2.18 on 2025-04-01 11:46

from django.db import migrations, models
from django.db.migrations import RunSQL

class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_remove_datapayload_raspberry_delete_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='humidity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_moisture_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_moisture_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raspberry',
            name='status',
            field=models.CharField(default='unassigned', max_length=50),
        ),

        RunSQL(
            """
            ALTER TABLE "Website_sensordata"
            ALTER COLUMN "soil_moisture" DROP DEFAULT;
            """,
            reverse_sql="""
            -- On ne sait pas quel était le DEFAULT, on peut laisser vide ou mettre un DEFAULT 0 --
            ALTER TABLE "Website_sensordata"
            ALTER COLUMN "soil_moisture"
            SET DEFAULT 0;
            """
        ),
        RunSQL(
            """
            ALTER TABLE "Website_sensordata"
            ALTER COLUMN "soil_moisture" TYPE jsonb 
            USING to_jsonb("soil_moisture");
            """,
            reverse_sql="""
            ALTER TABLE "Website_sensordata"
            ALTER COLUMN "soil_moisture" TYPE double precision
            USING "soil_moisture"::float8;
            """
        ),

        migrations.AlterField(
            model_name='sensordata',
            name='soil_moisture',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="Ensemble des valeurs d'humidité du sol"
            ),
        ),
    ]
