name: Deploy Django app with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }} 

    - name: Deploy to Server via SSH
      run: |
        # Vérification si Docker est bien installé sur le serveur
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker --version || echo Docker is not installed"
        
        # Cloner le projet si nécessaire
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          if [ ! -d /opt/eden/ ]; then
            echo "Le répertoire /opt/eden n'existe pas, création et clonage du projet..."
            git clone git@github.com:IPSI-EDEN/Website.git /opt/eden
          else
            echo "Le répertoire /opt/eden existe, mise à jour du projet..."
            cd /opt/eden
            git pull origin main
          fi

          cd /opt/eden

          # Vérifier les versions Docker et si le conteneur existe déjà
          sudo docker --version
          sudo docker ps

          # Arrêter et supprimer le conteneur existant
          sudo docker stop eden || true
          sudo docker rm eden || true

          # Vérifier si Dockerfile existe avant de construire
          if [ ! -f /opt/eden/Dockerfile ]; then
            echo "Dockerfile non trouvé !"
            exit 1
          fi

          # Construire l'image Docker
          sudo docker build -t django-app .

          # Lancer un nouveau conteneur
          sudo docker run -d -p 8000:8000 --name eden \
            -v /opt/eden:/app \
            -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
            django-app

          # Vérifier les logs du conteneur pour détecter les erreurs éventuelles
          sudo docker logs eden
        EOF
