name: Deploy Django app with Docker

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }} 

    - name: Deploy to Server via SSH
      run: |
        # Vérification si Docker est bien installé sur le serveur
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker --version || echo Docker is not installed"
        
        # Cloner le projet si nécessaire
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          if [ ! -d /opt/eden ]; then
            git clone git@github.com:IPSI-EDEN/Website.git /opt/eden
          fi

          cd /opt/eden

          # Vérifier les versions Docker et si le conteneur existe déjà
          docker --version
          docker ps

          # Arrêter et supprimer le conteneur existant
          docker stop django-web || true
          docker rm django-web || true

          # Construire l'image Docker
          docker build -t django-app .

          # Lancer un nouveau conteneur
          docker run -d -p 8000:8000 --name django-web \
            -v /opt/eden:/app \
            -v /opt/eden/db.sqlite3:/app/db.sqlite3 \
            -e DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
            django-app

          # Vérifier les logs du conteneur pour détecter les erreurs éventuelles
          docker logs django-web
        EOF
