name: Deploy Django app with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to Server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e  # Stop immediately if any command fails

          # Vérifier si Docker est installé
          if ! command -v docker &> /dev/null; then
            echo "Docker n'est pas installé. Veuillez l'installer avant de continuer."
            exit 1
          fi

          # Vérifier le répertoire de l'application
          if [ ! -d /opt/eden/ ]; then
            echo "Création du répertoire et clonage du projet..."
            git clone git@github.com:IPSI-EDEN/Website.git /opt/eden
          else
            echo "Mise à jour du projet existant..."
            cd /opt/eden
            if git fetch --dry-run; then
              git pull origin main
            else
              echo "Aucune mise à jour disponible."
            fi
          fi

          cd /opt/eden

          # Vérifier Dockerfile
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile manquant dans le projet !"
            exit 1
          fi

          # Arrêter et supprimer les conteneurs existants
          docker stop eden || true
          docker rm eden || true

          # Construire l'image Docker
          docker build -t django-app .

          # Lancer un nouveau conteneur
          docker run -e DB_NAME=eden -e DB_USER=${{ secrets.SERVER_USER }} -e DB_PASSWORD=${{ secrets.BDD_MDP }} -e DB_HOST=${{ secrets.SERVER_IP }} -e DB_PORT=5432 -e DB_SSLMODE=disable -d -p 8000:8000 --name eden \
            -v /opt/eden:/app \
            -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
            django-app
          
          docker exec -i eden python manage.py migrate
          
          # Vérification des logs pour erreurs
          sudo docker logs --tail 50 eden
        EOF
